# Generated by Django 2.2.12 on 2020-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200614_1629'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postits',
            field=models.ManyToManyField(null=True, to='todo.PostIt'),
        ),
    ]
