# Generated by Django 2.2.12 on 2020-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_postits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postits',
            field=models.ManyToManyField(to='todo.PostIt'),
        ),
    ]
