# Generated by Django 2.2.12 on 2020-06-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='postit',
        ),
        migrations.DeleteModel(
            name='PostIt',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
