# Generated by Django 2.2.12 on 2020-06-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_postit_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='postit',
        ),
        migrations.AddField(
            model_name='postit',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Task'),
        ),
    ]
