# Generated by Django 2.2.12 on 2020-06-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200614_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='PostItParent',
        ),
    ]
