# Generated by Django 2.2.12 on 2020-06-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200614_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='PostItParent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.PostIt'),
        ),
    ]
