# Generated by Django 2.2.12 on 2020-06-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200614_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='PostItParent',
        ),
        migrations.AddField(
            model_name='postit',
            name='tasks',
            field=models.ManyToManyField(to='todo.Task'),
        ),
    ]
