# Generated by Django 2.2.12 on 2020-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20200615_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='todo.Task'),
        ),
    ]
