# Generated by Django 2.2.12 on 2020-06-16 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0011_auto_20200615_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postit',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='postit',
            name='user',
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postit_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.PostIt')),
                ('task_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.Task')),
            ],
        ),
        migrations.CreateModel(
            name='PostItList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postit_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.PostIt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
